# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f12e27ec4a9bf1ca873900f5667dcb5433dc3d2e22d2925fefb3c948c3645ab477e6019abbb50dda63d9eb8a19adb105b1f7979e395def885e7858bca4fb875f

test:
  secret_key_base: 956b7ec7f78430053d7baa1811a461811c65324879b8444f95ce9319423623b8d65e5d6b63cde2a21d1413adbc27e821e27f4da47cfa738a3e22e5375974091a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
