require 'pg'
require 'pry'

db = PG.connect(dbname: 'facebook', host: 'localhost')

 #we don't want the code to quit if there's an error when working with databases. The begin block says to run this code, and if it fails, close connection to the db
begin
  db.exec('select * from people') do |result| #db.exec is an instance with a block (all r)
    # binding.pry
    result.each do |row|
      puts "#{row['first']} #{row['last']}"
    end
  end

  print 'full name: '
  name = gets.chomp.split #splits full name into first and last, aligns with db structure

  print 'dob: '
  dob = gets.chomp #chomp gets rid of the new line character that would be generated by hitting return

  print 'relationship: '
  relationship = gets.chomp

  print 'city: '
  city = gets.chomp

  #string assigned to variable below, string is in SQL query language
  sql = "insert into people (first, last, dob, relationship, city) values ('#{name.first}', '#{name.last}', '#{dob}', '#{relationship}', '#{city}') returning *"

  #executing sql variable
  new_user = db.exec(sql)

  binding.pry
  
  new_user.each { |user| puts "#{user['first']} #{user['last']} has now joined facebook. Haha! I have all yo data!" }
ensure
  db.close
end
