# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f8628a7e28821ad5f9cd1cc59189948fb39caba451561a26f615caab4c529f22e9a0e5616560429c8516bce1f57ae756932f75bf2d74b9f841bb5e8a24af30b

test:
  secret_key_base: 49a45f30881c835b716aeaed98c7e210d3db7f106c640456f80d731b4292e65a282636773811eade6463d5b493d95818c8310697c9cd925f09020e192868be1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
